@startuml
title Search for aircraft - Class Diagram

package "Aircraft Aggregate"{

    class Aircraft <<root>>{
           - registration_id: String
           - manufacturing_date: Date
           - seating_capacity: int
           - status: AircraftStatus
           ---
           +getDetails(): Map
    }

    class SearchAircraftService <<Domain Service>>{
           ---
           +searchAircrafts(String model, AircraftStatus status, Integer year): List<Aircraft>
    }

   interface AircraftRepository{
           ---
           + List<Aircraft> findByCriteria(String model, AircraftStatus status, Integer year)
   }

    SearchAircraftService ..> Aircraft : returns >
    SearchAircraftService ..> AircraftRepository : uses >
}

@enduml