@startuml
'https://plantuml.com/class-diagram

title Register an airport - Domain Model

package "Airport Aggregate" {

    class Airport <<root>> <<entity>> {
        - name: String
        - contact: String
    }

    Airport o--> "1" IATAcode
    Airport o--> "1" Timezone
    Airport o--> "1" Coordinates
    Airport o--> "1" AirportType
    Airport o--> "1" AirportLocation
    Airport o--> "1" AirportStatus
    Airport o--> "N" RunwayInfo

    class IATAcode <<value object>> {
        - iata_code: String
    }

    class Timezone <<value object>> {
        - abbreviation: String
        - utc_minutes: int
        - gmt_minutes: int
    }

    class Coordinates <<value object>> {
        - longitude: double
        - longitude_direction: char
        - latitude: double
        - latitude_direction: char
    }

    class AirportType <<entity>> {
        - name: String
        - description: String
    }

    class AirportLocation <<value object>> {
        - city: String
        - country: String
        - region: String
    }

    enum AirportStatus <<enum>> {
        OPERATIONAL
        CLOSED
        UNDER_MAINTENANCE
    }

    class RunwayInfo <<entity>> {
        - name: String
        - orientation: String
        - length: Float
    }
}

@enduml