@startuml
autonumber
title US106 - Register an Airport — Sequence Diagram

autoactivate on

actor "Backoffice Operator" as BO
participant "AirportController" as Ctrl
participant "RegisterAirportUseCase" as UC
participant "RegisterAirportService" as RegisterAirportService
database "AirportRepository" as Repo

BO -> Ctrl : POST /airports\n{ name, iataCode, timezone, coordinates, location, type, runways }

Ctrl -> Ctrl : extract username from JWT
alt User has authorization
    Ctrl -> UC : execute(name, iataCode, timezone, coordinates, location, type, runways)

    UC -> RegisterAirportService : registerAirport(name, iataCode, timezone, coordinates, location, type, runways)

    RegisterAirportService -> Repo : existsById(iataCode)
    return exists

    alt The Airport's IATA Code already exists
        RegisterAirportService --> UC : throw IllegalArgumentException("Airport already exists")
        UC --> Ctrl : throw ResponseStatusException(409, "Conflict")
        Ctrl --> BO : 409 Conflict\n{ message: "Airport already registered" }

    else The Airport's IATA Code does NOT exist

        RegisterAirportService -> Airport ** : new Airport(name, iataCode, timezone, coordinates, location, type, runways)

        RegisterAirportService -> Repo : save(airport)
        return airport(persisted)

        return airport
        return 201 Created\n{ iataCode, name, _links }
    end

else User does not have authorization
    Ctrl --> BO : 403 Forbidden\n{ message: "Not authorized to perform this action" }
end

@enduml