@startuml
'https://plantuml.com/class-diagram


autonumber

title US106 - Register an Airport — Simplified Sequence Diagram
actor "Backoffice Operator" as BO
participant ":System" as Sys

BO -> Sys: Register and airport
Sys -> BO: Request details \n(name, iataCode, timezone, coordinates, location, type, runways )

BO -> Sys: Inserts requested data
Sys --> BO: Shows data inserted to confirm

BO -> Sys: Confirms Data inserted
Sys --> BO: Registers the airport and displays a confirmation message

@enduml