@startuml
title Register an aircraft instance - Class Diagram

package "Aircraft Model Aggregate" {
    interface AircraftModelRepository {
        + Optional<AircraftModel> findByModelName(String modelName)
    }
}

package "Aircraft Aggregate"{

    class Aircraft <<root>>{
           - registration_id: String
           - manufacturing_date: Date
           - seating_capacity: int
           - status: AircraftStatus
           - last_maintenance: Date
           - days_since_last_maintenance: int
           ---
           +Aircraft(registrationId, model, manufacturingDate, seatingCapacity, status)
    }

    enum AircraftStatus <<enum>> {
        ACTIVE
        INACTIVE
        UNDER_MAINTENANCE
    }

    class RegisterAircraftService <<Domain Service>>{
           ---
           +registerAircraft(String registrationNumber, String modelName, int seatingCapacity, Date manufacturingDate, AircraftStatus status): Aircraft
    }

   interface AircraftRepository{
           ---
           + boolean existsById(String registrationNumber)
           + Aircraft save(Aircraft)
   }

    RegisterAircraftService ..> Aircraft : creates >
    RegisterAircraftService ..> AircraftRepository : uses >
    RegisterAircraftService ..> AircraftModelRepository : uses >
    Aircraft --> AircraftStatus : has >
}

@enduml