@startuml
title US202 - Register Aircraft Model with Diagram - Domain Model

package "Aircraft Aggregate" {

    class AircraftModel <<root>> <<entity>> {
        - manufacturer: String
        - model_name: String
    }

    class CruisingSpeed <<value object>> {
        - speed: float
    }

    class FuelCapacity <<value object>> {
        - capacity: float
    }

    class TechnicalDiagram <<value object>> {
        - diagram_url: String
    }

    AircraftModel o--> "1" CruisingSpeed
    AircraftModel o--> "1" FuelCapacity
    AircraftModel o--> "0..1" TechnicalDiagram
}
@enduml