@startuml
'https://plantuml.com/class-diagram


hide circle
hide methods
skinparam classAttributeIconSize 0

package "Aircraft Aggregate"{
class AircraftModel <<entity>> {
    - manufacturer: String
    - model_name: String
    - cruising_speed: float
    - fuel_capacity: float
    - max_range: float
    - technical_diagram: String
}

class Aircraft <<entity>> <<root>> {
    - registration_ID: String
    - manufacturing_date: Date
    - seating_capacity: int
    - last_maintenance: Date
    - days_since_last_maintenance: int
}

Aircraft o--> AircraftStatus
Aircraft --> AircraftModel : "has an"

class AircraftStatus <<enum>> {
    - ACTIVE: int
    - IN_FLIGHT: int
    - INACTIVE: int
    - UNDER_MAINTENANCE: int
}
}

package "Airport Aggregate" {
    class Airport <<entity>> <<root>> {
        - iata_code: String
        - name: String
        - city: String
        - country: String
        - runway_information: List<String>
    }

    Airport o--> "N" RunwayInfo
    Airport o--> AirportStatus
    Airport o--> "N" ContactInfo

    class ContactInfo <<value object>> {
        - type: String
        - contact_detail: String
    }

    class RunwayInfo <<entity>> {
        - name: String
        - length: float
        - orientation: String
    }

    class AirportStatus <<enum>> {
        - OPERATIONAL: int
        - CLOSED: int
        - UNDER_MAINTENANCE: int
    }
}

package "Flight Aggregate"{


class Flight <<entity>> <<root>> {
    - flight_id: String
    - scheduled_datetime: Date
    - delayed_hours: float
    - flight_duration: Date
}

Flight o--> FlightStatus


class FlightStatus <<enum>> {
    - SCHEDULED: int
    - OCCURRING: int
    - DELAYED: int
    - COMPLETED: int
    - CANCELED: int
}
}

package "Route Aggregate"{
class Route <<entity>> <<root>>{
    - route_id: String
    - active: boolean
    - estimated_flight_minutes: int
    - min_range_required: float
    - min_capacity_required: int
}
}

package "Maintenance Aggregate" {
MaintenanceRecord o--> "N" MaintenanceParts : "uses"
class MaintenanceRecord <<entity>> <<root>> {
    - start_date: Date
    - expected_duration_hours: float
    - end_date: Date
    - check_list_status: String
    - notes: String
}

class MaintenanceParts <<entity>>{
    - partNumber: int
    - stockQuantity: int
    - name: String
    - Description: String
}

}

package "MaintenanceTemplate Aggregate"{
class MaintenanceTemplate <<entity>> <<root>> {
    - template_name: String
    - aircraft_model: String
    - checklist: List<String>
    - scheduled_maintenance: Date
}

}
MaintenanceRecord --> MaintenanceTemplate : "built on"
Airport "1" <-- "N" AircraftModel : "Confirmed by   "
Route --> "2" Airport : "Origin / Destination"
MaintenanceRecord --> Aircraft : "Exected in"
Flight --> Route : "follows"
Flight --> Aircraft : "executed by"

@enduml