@startuml
'https://plantuml.com/class-diagram


hide circle
hide methods
skinparam classAttributeIconSize 0

package "Aircraft Aggregate"{
class AircraftModel <<entity>> {
    - manufacturer: String
    - model_name: String
    - cruising_speed: float
    - fuel_capacity: float
    - max_range: float
    - technical_diagram: String
}

class Aircraft <<entity>> <<root>> {
    - registration_ ID: String
    - manufacturing_date: Date
    - seating_capacity: int
    - last_maintenance: Date
    - days_since_last_maintenance: int
}

Aircraft *--> AircraftStatus
Aircraft --> AircraftModel : "has an"

class AircraftStatus <<enum>> {
    - active: int
    - in_flight: int
    - inactive: int
    - under_maintenance: int
}
}

package "Airport Aggregate" {
    class Airport <<entity>> <<root>> {
        - iata_code: String
        - name: String
        - city: String
        - country: String
        - timezone: Date
        - coordinates: String
    }

    Airport o--> "N" RunwayInfo
    Airport o--> AirportStatus
    Airport "1" o--> "N" ContactInfo

    class ContactInfo <<value object>> {
        - type: String
        - contact_detail: String
    }

    class RunwayInfo <<entity>> {
        - name: String
        - length: float
        - orientation: String
    }

    class AirportStatus <<enum>> {
        - operational: int
        - closed: int
        - under_maintenance: int
    }
}

package "Flight Aggregate"{


class Flight <<entity>> <<root>> {
    - flight_id: String
    - scheduled_datetime: Date
    - delayed_hours: float
    - flight_duration: float
}

Flight *--> FlightStatus


class FlightStatus <<enum>> {
    - scheduled: int
    - flying: int
    - delayed: int
    - completed: int
    - canceled: int
}
}

package "Route Aggregate"{
class Route <<entity>> <<root>>{
    - route_id: String
    - active: boolean
    - estimated_flight_time: int
    - min_range: float
    - min_capacity: int
}

'duvida para o professor, há necessidade de ter um routeRecord??'

class RouteRecord <<value object>>{
    - record_date: Date
    - active: boolean
    - estimated_flight_time: int
    - min_range: float
    - min_capacity: int
}
Route *--> RouteRecord
}

package "Maintenance Aggregate" {
class MaintenanceRecord <<entity>> <<root>> {
    - start_date: Date
    - expected_duration_hours: float
    - end_date: Date
    - check_list_status: String
    - notes: String
}
}


package "Inventory Aggregate"{

class MaintenanceParts <<entity>> <<root>>  {
    - partNumber: int
    - stockQuantity: int
    - name: String
    - Description: String
}

}

package "MaintenanceTemplate Aggregate"{
class MaintenanceTemplate <<entity>> <<root>> {
    - template_name: String
    - template_type: String
    - aircraft_model: String
    - checklist: List<String>
    - scheduled_maintenance: Date
}

}


MaintenanceParts "  N"  <- "1" MaintenanceRecord : "    Uses   "
MaintenanceRecord --> MaintenanceTemplate : "built on"
Airport "1" --> "N" AircraftModel : "Certified by   "
Route --> "2" Airport : "Origin / Destination"
MaintenanceRecord --> Aircraft : "Executed in"
Flight --> Route : "does"
Flight --> Aircraft : "executed by"

@enduml