@startuml
autonumber

title US102 - Register an Aircraft Instance — Simplified Sequence Diagram
actor "Air Transport Company Collaborator (ATCC)" as ATCC
participant ":System" as Sys

ATCC -> Sys: Register a specific aircraft instance
Sys --> ATCC: Request details \n(registration number, model name, seating capacity, manufacturing date, current status)

ATCC -> Sys: Inserts requested data
Sys --> ATCC: Shows data inserted to confirm

ATCC -> Sys: Confirms data inserted
Sys --> ATCC: Registers the aircraft and displays a confirmation message

@enduml