@startuml
autonumber

title US202 - Register Aircraft Model with Diagram — Simplified Sequence Diagram
actor "Backoffice Operator" as BO
participant ":System" as Sys

BO -> Sys: Register an aircraft model with an optional technical diagram
Sys --> BO: Request details \n(manufacturer, model name, max capacity, ..., optional technical diagram)

BO -> Sys: Inserts requested data
Sys --> BO: Shows data inserted to confirm

BO -> Sys: Confirms data inserted
Sys --> BO: Registers the aircraft model and displays a confirmation message

@enduml